### ISSUE TITLE
Cloudflare is blocking requests without clearance token

### ISSUE THREAD

**Issue by apollotsantos** [pascalroget/whatsgpt#1]
The API already updated to include the token. I've also patched your code but I keep getting error 503

**Comment by pascalroget** [comment]
Do you want to pull request your patch and I'll take a look after?

**Comment by pascalroget** [comment]
No and I think there’s a few things to refactor and I’m not home atm but
I’ll look again later

**Comment by pascalroget** [comment]
Looks like the situation has changed again and chatgpt package now uses Puppeteer to log into OpenAI, so I've modified the code again.

Unfortunately I can't test it now because ChatGPT is at max capacity due to overusage

**Comment by pascalroget** [comment]
It seems to work with the authentication method given on chatgpt package docs
