### ISSUE TITLE
Chrome starting windows issue

### ISSUE THREAD

**Issue by pateutz1** [pascalroget/whatsgpt#4]
I tried on windows, I've set up the CHROME_PATH in env and also tried directly in index.js but without success.
I've also tried with chromium but the same thing. 
I can't make it work on windows.

**Comment by pascalroget** [comment]
This is a puppeteer issue. Have you had any luck?

**Comment by dorlanpabon** [comment]
Amigo, al parecer es algo de como se esta manejando el path en el proyecto, pues al colocar

`// Download chrome runtime from
import puppeteer from "puppeteer";

//Download chrome runtime executable from
var browser = await puppeteer.launch({ executablePath: process.env.CHROME_PATH, headless: false });`

Todo funciona bien abriendo chrome

**Comment by dorlanpabon** [comment]
async function getBrowser(launchOptions) {
  const macChromePath = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
  return puppeteer.launch({
    headless: false,
    args: ["--no-sandbox", "--exclude-switches", "enable-automation"],
    ignoreHTTPSErrors: true,
    executablePath: macChromePath,
    ...launchOptions
  });
},

Creo que por aqui podria estar el problema

**Comment by dorlanpabon** [comment]
La solución fácil, pero no adecuada, es cambiar esa ruta jiji, la solución adecuada es ver por qué no llega nada en lauchOptions, estoy revisando ello a ver si encuentro algo.
